version: '3.4'

services:
  db:
    image: 'mysql:5.7.4'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - './.docker/data/db:/var/lib/mysql'
      - './.docker/mnt:/mnt'
  elasticsearch:
    image: 'elasticsearch:7.12.0'
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - network.bind_host=0.0.0.0
      - network.host=0.0.0.0
      - discovery.type=single-node
  fpm:
    build:
      context: .
    volumes:
      - './:/var/www/html'
      - './.docker/vendor:/var/www/html/vendor'
      - './.docker/generated:/var/www/html/generated'
      - './.docker/pub:/var/www/html/pub'
      - './.docker/mnt:/mnt'
      - './.docker/xdebug:/var/log/xdebug'
  web:
    image: 'nginx:1.20.0-alpine'
    env_file:
      - .env
    volumes:
      - './:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './.docker/vendor:/var/www/html/vendor'
      - './.docker/generated:/var/www/html/generated'
      - './.docker/pub:/var/www/html/pub'
    ports:
      - '8000:80'
    depends_on:
      - db
      - fpm
