<?php
/** @var News $block */

use Dabilo\MiniWindow\Block\Widget\News;

?>
<?php
$result = $block->getNewsInformation();
$data = simplexml_load_string($result);
$items = $data->channel->item;

?>

<?php if($block->getData('news')): ?>
    <h2 class='news'><?php echo $block->getData('news'); ?>
    </h2>
                <?php
                foreach($items as $item)//lap
                {
                $title = $item->title;
                $des = $item->descriptions;

                $link = $item->link;
                ?>

                <table width="800" border="1">
                    <tr>
                        <td style="color:#FF0000; font-weight:bold; text-decoration:none"><a
                            href="<?  echo $link;?>"/><? echo $title ?></td>
                    </tr>
                    <tr>
                        <td><? echo $des ?></td>
                    </tr>
                </table>
                <?
                }
                ?>
<?php endif; ?>

