<?php
/** @var Weather $block */

use Dabilo\MiniWindow\Block\Widget\Weather;

?>
<?php
$result = $block->getWeatherInformation();
$main = $result->weather[0]['main'];
$description = $result->weather[0]['description'];
$temp = $result->main['temp'];
$temp_min = $result->main['temp_min'];
$temp_max = $result->main['temp_max'];
$umid = $result->main['humidity'];
?>

<?php if($block->getData('news')): ?>
    <h2 class='news'><?php echo $block->getData('news'); ?>
    <?php echo "The weather in Hanoi is $main, probably with $description".'<br>' .
    "The temperatutur now is $temp degree, with minimun for today of $temp_min degree and maximun $temp_max degree." . '<br>' .
    "The humidity is $umid%"; ?>
    </h2>
<?php endif; ?>

